# Generated by Django 2.1.4 on 2019-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('i', 'image')], max_length=1)),
                ('image', models.BinaryField(blank=True)),
                ('image_preview', models.BinaryField(blank=True)),
            ],
        ),
    ]
