# Generated by Django 2.1.4 on 2019-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.BinaryField(blank=True, max_length=1048576),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_preview',
            field=models.BinaryField(blank=True, max_length=1048576),
        ),
    ]
