# Generated by Django 2.1.4 on 2019-01-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20190103_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='id',
        ),
        migrations.AddField(
            model_name='media',
            name='timestamp',
            field=models.BigIntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
    ]
