# Generated by Django 2.1.4 on 2019-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_auto_20190103_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='image',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='image_preview',
            new_name='preview_data',
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='timestamp',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
