# Generated by Django 2.1.4 on 2019-01-12 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_auto_20190106_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('user_id', models.CharField(max_length=33, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^U[0-9a-f]{32}$', message='Invalid LINE User ID')])),
                ('display_name', models.CharField(max_length=100)),
                ('status_message', models.CharField(max_length=500)),
                ('picture_url', models.URLField()),
            ],
        ),
    ]
