# Generated by Django 2.1.4 on 2019-01-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0008_auto_20190112_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('timestamp', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.Friends')),
            ],
        ),
    ]
